### ISSUE TITLE
trying to do install -- puppet agent can't find pip but it is there - centos 7

### ISSUE THREAD

**Issue by SteveDevOps** [evenup/evenup-curator#24] opened 2015-01-13 15:26 UTC
Greets,
I'm testing install of curator via puppet. I was able to get python and pip installed via a separate approved python module. Curator job is setup successfully via the separate job class, but it can't do the main install because the agent can't find pip for some reason. It is present on the target system.. please advise.. I am testing on a centos 7 vm.

Info: Applying configuration version '1421162287'
Error: Could not update: Could not locate the pip command.
Wrapped exception:
Could not locate the pip command.
Error: /Stage[main]/Curator/Package[elasticsearch-curator]/ensure: change from absent to latest failed: Could not update: Could not locate the pip command.
Notice: Finished catalog run in 2.93 seconds

from system messages log:

Jan 13 10:17:54 pnode-test puppet-agent[14143]: Retrieving pluginfacts
Jan 13 10:17:54 pnode-test puppet-agent[14143]: Retrieving plugin
Jan 13 10:17:59 pnode-test puppet-agent[14143]: Loading facts
Jan 13 10:18:04 pnode-test puppet-agent[14143]: Caching catalog for pnode-test.evestment.local
Jan 13 10:18:04 pnode-test puppet-agent[14143]: (at /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/type/package.rb:430:in `block (3 levels) in <module:Puppet>')
Jan 13 10:18:05 pnode-test puppet-agent[14143]: Applying configuration version '1421162287'
Jan 13 10:18:06 pnode-test puppet-agent[14143]: Could not update: Could not locate the pip command.
Jan 13 10:18:06 pnode-test puppet-agent[14143]: Wrapped exception:
Jan 13 10:18:06 pnode-test puppet-agent[14143]: Could not locate the pip command.
Jan 13 10:18:06 pnode-test puppet-agent[14143]: (/Stage[main]/Curator/Package[elasticsearch-curator]/ensure) change from absent to latest failed: Could not update: Could not locate the pip command.
Jan 13 10:18:08 pnode-test puppet-agent[14143]: Finished catalog run in 2.93 seconds

[root@pnode-test elasticsearch]# pip

Usage:   
  pip <command> [options]

Commands:
  install                     Install packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  list                        List installed packages.
  show                        Show information about installed packages.
  search                      Search PyPI for packages.
  wheel                       Build wheels from your requirements.
  zip                         DEPRECATED. Zip individual packages.
  unzip                       DEPRECATED. Unzip individual packages.
  bundle                      DEPRECATED. Create pybundles.
  help                        Show help for commands.

General Options:
  -h, --help                  Show help.
  -v, --verbose               Give more output. Option is additive, and can be used up to 3 times.
  -V, --version               Show version and exit.
  -q, --quiet                 Give less output.
  --log-file <path>           Path to a verbose non-appending log, that only logs failures. This log is active by default at /root/.pip/pip.log.
  --log <path>                Path to a verbose appending log. This log is inactive by default.
  --proxy <proxy>             Specify a proxy in the form [user:passwd@]proxy.server:port.
  --timeout <sec>             Set the socket timeout (default 15 seconds).
  --exists-action <action>    Default action when a path already exists: (s)witch, (i)gnore, (w)ipe, (b)ackup.
  --cert <path>               Path to alternate CA bundle.

[root@pnode-test bin]# pwd
/usr/bin
[root@pnode-test bin]# ls -al pip*
-rwxr-xr-x. 1 root root 281 Dec 18 03:48 pip
-rwxr-xr-x. 1 root root 283 Dec 18 03:48 pip2
-rwxr-xr-x. 1 root root 287 Dec 18 03:48 pip2.7

**Comment by SteveDevOps** [comment] 2015-01-13 15:50
ok.. fyi.. solved by making symbolic link in /usr/bin called pip-python and pointed to pip.
Had found this thread via google:
http://thr3ads.net/puppet-users/2013/06/2652639-Pip-provider-fails-on-RedHat-osfamily-when-pip-not-installed-via-RPM-Could-not-locate-the-pip

**Comment by jlambert121** [comment] 2015-01-13 18:06
Glad you got that figured out!  I'm trying to figure out if there's anything we can do in the module to avoid this in the future for someone else, but I'm not sure there is.  Any thoughts?

I'm just starting to get my modules tested in CentOS7 so I hadn't run into this yet.

**Comment by SteveDevOps** [comment] 2015-01-20 21:32
can you do a bandaid for now?.. if on rhel / centos 7 -- sniff for pip-python in /usr/bin .. if not there.. make symlink  -- or if 7.. utilize /usr/bin/pip instead..  or post a warning message so user is aware for now -- I imagine this could be epel repo for 7 not caught up to things.. dunno

**Comment by jlambert121** [comment] 2015-01-20 22:32
I'm not sure what type of bandaid to apply for this as the issue is with the puppet pip provider and not something with this module specifically.  I found [PL ticket 3829](https://tickets.puppetlabs.com/browse/PUP-3829) that looks like it will resolve this, but I'm not sure if it will make it in 3.7.4 since it's not tagged with that.

Do you have an idea on how to patch this?

**Comment by jlambert121** [comment] 2015-03-25 21:03
Closing this issue as it's a puppet problem, not anything with this module.  The PL ticket has been resolved and should be in the next releases.

**Closed by jlambert121** 2015-03-25 21:03 UTC

**Comment by SteveDevOps** [comment] 2015-08-11 11:56
Fyi, this will happen again if folks on CentOS upgrade to 6.7. I had sym link and it was removed by upgrade process, had to put back.

**Comment by SteveDevOps** [comment] 2015-08-11 12:14
update.. I upgraded stankevich-python (wasn't on latest 1.9.6) , removed symlink on target CentOS 6.7 vm to see if this module upgrade would fix.. ran puppet agent -t  -- no luck. Had to manually put back.

**Comment by fabiendelpierre** [comment] 2015-10-02 14:47
I was wracking my brain trying to figure this out on my own for days until I simply googled it and ended up here, 10 seconds later :dizzy_face:
I thought it was an issue with this module until I simply tried the below without invoking this module at all:
```
package { 'elasticsearch-curator': 
  ensure => present,
  provider => 'pip',
}
```
...and got the same error.
[This](https://github.com/puppetlabs/puppet/blob/master/lib/puppet/provider/package/pip.rb#L43-L47) is why. Knowing this, I added the symlink bandaid in my wrapper class and that fixed it after some wrangling with resource relationships to make absolutely sure the `/usr/bin/python-pip` to `/usr/bin/pip` symlink is created before this module's code is run.
This is what did it for me:
```
class myclass {
  file { '/usr/bin/pip-python':
    ensure => 'link',
    target => '/usr/bin/pip',
  } ->
  class { 'curator': }
}
```
Silly that we have to do this but it works. Using CentOS 6.6 by the way.

**Comment by flysen** [comment] 2017-01-05 10:53
**#RHEL7.2#**
##Need to install epel (stahnma-epel)->python-pip->fix symlink->add repo->install curator

```
class { 'epel':} ->
        package { 'python2-pip': ensure => installed, } ->
        file { '/usr/bin/pip-python':
                ensure  => 'link',
                target  => '/usr/bin/pip',
        } ->
        yumrepo { 'curator-4':
                enabled  => 1,
                descr    => 'CentOS/RHEL 7 repository for Elasticsearch Curator 4.x packages',
                baseurl  => 'http://packages.elastic.co/curator/4/centos/7',
                gpgcheck => 1,
                gpgkey => 'http://packages.elastic.co/GPG-KEY-elasticsearch',
        } ->
        class { 'curator':
                package_name => 'python-elasticsearch-curator',
                provider     => 'yum'
        }

```
